admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }
    requirements:
        _method: GET

page.index:
    path:     /pages
    defaults: { _controller: AdminBundle:Page:index }
    requirements:
        _method: GET

page.edit:
    path:     /pages/{id}/edit
    defaults: { _controller: AdminBundle:Page:edit }

page.create:
    path:     /pages/create
    defaults: { _controller: AdminBundle:Page:create }

