login:
    path:     /login
    defaults: { _controller: AuthBundle:Default:login }
login_check:
    path:     /login_check
    options: { i18n: false }
logout:
    path:     /logout
    defaults: { _controller: AuthBundle:Default:logout }
    options: { i18n: false }

register:
    path:     /register
    defaults: { _controller: AuthBundle:Default:register }

admin_login:
    path: /admin/login
    defaults: { _controller: AuthBundle:Admin:login }

admin_login_check:
    path: /admin/login_check

admin_logout:
    path: /admin/logout
