<?php

namespace AdminBundle\Repository;

use AdminBundle\Traits\Repository\BasicTrait;
use AdminBundle\Traits\Repository\TranslationTrait;
use Doctrine\ORM\Mapping;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    use BasicTrait;
    use TranslationTrait;

    public function getFullList($table, $locale, $fields) {
        return $this->init($table)
            ->joinTranslations($table, $locale)
            ->query()
            ->select($fields)
            ->getQuery()
            ->getResult();
    }

}
