<?php

namespace AdminBundle\Repository;

use AdminBundle\Traits\Repository\BasicTrait;
use AdminBundle\Traits\Repository\TranslationTrait;
use Gedmo\Translatable\TranslatableListener;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    use BasicTrait;
    use TranslationTrait;

    public function getFullList($table, $locale, $use_default_locale = false) {
        return $this
            ->init($table)
            ->render()
            ->joinTranslations($locale, $use_default_locale)
            ->query()
            ->getResult();
    }

}
