login:
    path:     /login
    defaults: { _controller: AuthBundle:Default:login }

login_check:
    path:     /login_check
    options: { i18n: false }

register:
    path:     /register
    defaults: { _controller: AuthBundle:Default:register }

logout:
    path:     /logout
    defaults: { _controller: AuthBundle:Default:logout }
    options: { i18n: false }