<?php

namespace MyAdmin\ContentBundle\Repository;

use MyAdmin\AdminBundle\Classes\AdminAbstractRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends AdminAbstractRepository
{

    public $findMethod = "findWithTranslations";

}
