#HERE WILL BE ALL MODULES CONNECTED EXCEPT AUTH AND FRONT PART's

admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }
    requirements:
        _method: GET

content:
    resource: "@ContentBundle/Resources/config/routing.yml"
    prefix: /
